services:
  app:
    build: .
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - postgres

  postgres:
    container_name: "postgresql"
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=soundcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgres/data
    restart: always
    networks:
      - main

networks:
  main:

volumes:
  postgres:
