name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/development.txt
    - name: Linting & Code Formatting
      run: pre-commit run --all-files
    - name: Run Tests
      env:
        DEBUG: True
        SECRET_KEY: django-insecure-jzfxvvwsh^p+fn4eqth#x2!o7=2o7=e+-@0p0^v_+h*@@3iu2y
      run: |
        python manage.py test
